
''' CONSTANTS '''

# Tiles
MARGIN = 2
TILE_SIZE = 60

# Grid
GRID_SIZE = 8
OBSTACLE_COUNT = 10

# Colors
SEEKER_COLOR = '#FF6430'
HIDER_COLOR = '#30FFCF'
WALL_COLOR = (250, 218, 94)
BACKGROUND = '#202020'

# Settings
MAX_DISTANCE = 3

# GUI
WINDOW_WIDTH = TILE_SIZE * GRID_SIZE + GRID_SIZE * MARGIN
WINDOW_HEIGHT = TILE_SIZE * GRID_SIZE + GRID_SIZE * MARGIN

